name: Terraform Plan

on: workflow_dispatch

jobs:
  plan:
    name: plan
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare secrets
        run: mkdir -p $HOME/.passage && echo "$AGE_SECRET_KEY_FILE" > $HOME/.passage/identities && nix run .\#export-secrets
        env:
          AGE_SECRET_KEY_FILE: ${{ secrets.AGE_SECRET_KEY_FILE }}
      
      # Nix-specific logic begins here
      - name: Test the nix setup
        run: source sourceme && nix run .\#plan
