name: Terraform Plan
# this pr should trigger ci cd
on: 
  workflow_dispatch:
  issue_comment:
    types: [created]
  
jobs:
  plan:
    name: plan
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/plan')
    runs-on: ubuntu-22.04
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare secrets
        run: mkdir -p $HOME/.passage && echo "$AGE_SECRET_KEY_FILE" > $HOME/.passage/identities && nix run .\#export-secrets
        env:
          AGE_SECRET_KEY_FILE: ${{ secrets.AGE_SECRET_KEY_FILE }}
      
      # Nix-specific logic begins here
      - name: Terraform plan
        run: source sourceme && nix run .\#plan
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
